[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
runner = "qemu-system-riscv64 -m 1024 -M virt -nographic -bios none  -smp 8 -kernel "
# runner = "qemu-system-riscv64 -M virt -cpu rv64 -nographic -d guest_errors,unimp -smp 4 -m 128M -drive if=none,format=raw,file=hdd.dsk,id=foo -device virtio-blk-device,scsi=off,drive=foo -serial mon:stdio -bios none -device virtio-rng-device -device virtio-gpu-device -device virtio-net-device -device virtio-tablet-device -device virtio-keyboard-device -kernel "

rustflags = [
    # "-Clink-arg=-Tsrc/linker.ld", 
    # "-Cforce-frame-pointers=yes"

    # LLD (shipped with the Rust toolchain) is used as the default linker
    "-C", "link-arg=-Tlink.x",
]
